import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import game, { initial, validate, apply, view, battle, counterChance } from '../../../stories/hof-cli/game.mjs';
import { ENEMIES } from '../../../stories/hof-cli/content.mjs';
const { Session } = await import(pathToFileURL(path.join(process.env.HOF_ENGINE, 'src/cli/session.mjs')).href);
const { Store } = await import(pathToFileURL(path.join(process.env.HOF_ENGINE, 'src/cli/storage.mjs')).href);
const quiet = { integer: (_min, max) => max };
const deadly = { integer: (min, max) => max === 100 ? min : max };
const walk = (s, ids, random = quiet) => { for (const id of ids) { const r = apply(s, id, random); assert.equal(r.kind, 'accepted', `${id}: ${r.reason}`); } return s; };
const shop = () => walk(initial(), ['begin', 'cliff', 'ore']);
const elite = () => walk(shop(), ['leave', 'fight', 'grove', 'forage', 'curse']);
const victory = () => walk(shop(), ['buy-sabre', 'buy-coat', 'buy-bread', 'leave', 'fight', 'grove', 'forage', 'bless', 'fight', 'light']);
const death = () => { const s = elite(); walk(s, ['fight'], deadly); return s; };
const choose = (s, ids) => { for (const id of ids) assert.equal(s.choose(id).kind, 'accepted', id); };
test('HOF-U01 initial state and actual pinned Session are compatible', () => { assert.equal(validate(initial()), true); assert.match(new Session(game, 42).query('status'), /生命20\/20/); });
test('HOF-U02 counter probability has a nonzero five percent floor', () => assert.equal(counterChance(65, 3, true, false), 5));
test('HOF-U03 counter probability has a ninety-five percent ceiling', () => assert.equal(counterChance(100, 0, false, true), 95));
test('HOF-U04 counter threshold is inclusive and only hits roll damage', () => {
  const calls = []; const rng = { integer(min, max, purpose) { calls.push({ min, max, purpose }); return max === 100 ? 65 : 2; } };
  const r = battle(ENEMIES.birds, 20, 0, 0, false, false, rng); assert.equal(r.hits, 3); assert.equal(r.hp, 14); assert.equal(calls.length, 6); assert.match(calls[1].purpose, /有效伤害/);
});
test('HOF-U05 roll above threshold causes no counter or damage draw', () => { const calls = []; const r = battle(ENEMIES.birds, 20, 0, 0, false, false, { integer: (a, b) => { calls.push(b); return 66; } }); assert.equal(r.damage, 0); assert.deepEqual(calls, [100, 100, 100]); });
test('HOF-U06 weapon reduces probability but never potential attack count', () => { const a = battle(ENEMIES.keeper, 20, 0, 0, false, false, quiet), b = battle(ENEMIES.keeper, 20, 3, 0, false, false, quiet); assert.equal(a.potential, 8); assert.equal(b.potential, 8); assert.equal(a.chance - b.chance, 45); });
test('HOF-U07 whole battle can naturally be damage free', () => { const r = battle(ENEMIES.rats, 20, 0, 0, false, false, quiet); assert.equal(r.won, true); assert.equal(r.hp, 20); assert.equal(r.hits, 0); });
test('HOF-U08 armor reduces actual effective damage', () => { const r = battle(ENEMIES.birds, 20, 0, 1, false, false, deadly); assert.equal(r.damage, 9); assert.equal(r.hp, 11); assert.equal(r.hits, 3); });
test('HOF-U09 armor may absorb an effective hit without forced damage', () => { const r = battle(ENEMIES.birds, 20, 0, 3, false, false, { integer: () => 1 }); assert.equal(r.hits, 3); assert.equal(r.damage, 0); assert.equal(r.hp, 20); });
test('HOF-U10 death stops remaining attack and damage draws', () => { let n = 0; const r = battle(ENEMIES.keeper, 3, 0, 0, false, false, { integer(a, b) { n++; return b === 100 ? 1 : b; } }); assert.equal(r.potential, 8); assert.equal(r.checked, 1); assert.equal(r.damage, 3); assert.equal(n, 2); assert.equal(r.won, false); });
test('HOF-U11 blessing and curse change only counter probability', () => { assert.equal(counterChance(75, 1, true, false), 45); assert.equal(counterChance(75, 1, true, true), 60); });
test('HOF-U12 first departure separates fresh run from profile', () => { const s = initial(); walk(s, ['begin']); assert.equal(s.run.id, 1); assert.equal(s.run.node, 'fork'); assert.deepEqual(s.profile, { wins: 0, deaths: 0, retreats: 0, unlocks: [] }); });
test('HOF-U13 first routes have different real food costs', () => { const a = walk(initial(), ['begin', 'marsh']), b = walk(initial(), ['begin', 'cliff']); assert.equal(a.run.food, 6); assert.equal(b.run.food, 7); assert.notEqual(a.run.node, b.run.node); });
test('HOF-U14 zero food permits only one legal retreat settlement', () => { const s = shop(); s.run.food = 0; assert.deepEqual(view(s).choices.map(x => x.id), ['retreat']); walk(s, ['retreat']); assert.equal(s.profile.retreats, 1); assert.equal(s.profile.wins, 0); const before = structuredClone(s); assert.equal(apply(s, 'retreat', quiet).kind, 'refused'); assert.deepEqual(s, before); });
test('HOF-U15 insufficient branch cost refuses without mutation or RNG', () => { const s = walk(initial(), ['begin']); s.run.food = 1; const before = structuredClone(s); assert.equal(apply(s, 'marsh', { integer() { throw new Error('must not draw'); } }).kind, 'refused'); assert.deepEqual(s, before); });
test('HOF-U16 marsh event uses real Session RNG and named consumption', () => { const s = new Session(game, 42); choose(s, ['begin', 'marsh', 'fish']); const snap = s.snapshot(); assert.equal(snap.rng.draws, 1); assert.equal(snap.log.at(-1).random[0].purpose, '芦苇渡口漂粮数量'); assert.equal(snap.state.run.node, 'shop'); });
test('HOF-U17 food trade checks event and travel costs before rewards', () => { const s = walk(initial(), ['begin', 'marsh']); s.run.food = 2; const before = structuredClone(s); assert.equal(apply(s, 'trade', quiet).kind, 'refused'); assert.deepEqual(s, before); s.run.food = 3; walk(s, ['trade']); assert.equal(s.run.food, 0); assert.equal(s.run.gold, 14); });
test('HOF-U18 cliff ore consumes health and awards gold once', () => { const s = shop(); assert.equal(s.run.hp, 16); assert.equal(s.run.gold, 16); assert.equal(s.run.food, 6); const before = structuredClone(s); assert.equal(apply(s, 'ore', quiet).kind, 'refused'); assert.deepEqual(s, before); });
test('HOF-U19 buying weapon pays once and actually equips it', () => { const s = shop(); walk(s, ['buy-sabre']); assert.equal(s.run.gold, 10); assert.equal(s.run.weapon, 'sabre'); assert.deepEqual(s.run.bag, ['sabre']); });
test('HOF-U20 rejected purchase leaves fee and inventory untouched', () => { const s = shop(); s.run.gold = 1; const before = structuredClone(s); assert.equal(apply(s, 'buy-sabre', quiet).kind, 'refused'); assert.deepEqual(s, before); });
test('HOF-U21 duplicate equipment is a named refusal not another charge', () => { const s = shop(); walk(s, ['buy-coat']); const before = structuredClone(s); assert.equal(apply(s, 'buy-coat', quiet).reason, '已经拥有这件装备'); assert.deepEqual(s, before); });
test('HOF-U22 changing equipped weapon never stacks both ratings', () => { const s = shop(); walk(s, ['buy-knife', 'buy-sabre', 'equip-knife', 'leave', 'fight']); assert.equal(s.run.weapon, 'knife'); assert.match(s.run.last, /概率50%/); });
test('HOF-U23 tonic heals to cap and consumes exactly one bottle', () => { const s = shop(); walk(s, ['buy-tonic', 'tonic']); assert.equal(s.run.hp, 20); assert.deepEqual(s.run.bag, []); });
test('HOF-U24 full health rejects tonic without consuming bottle', () => { const s = shop(); walk(s, ['buy-tonic']); s.run.hp = 20; const before = structuredClone(s); assert.equal(apply(s, 'tonic', quiet).reason, '生命已满'); assert.deepEqual(s, before); });
test('HOF-U25 shop enforces three tonic carry limit without charge', () => { const s = shop(); walk(s, ['buy-tonic', 'buy-tonic', 'buy-tonic']); const before = structuredClone(s); assert.equal(apply(s, 'buy-tonic', quiet).reason, '最多携带3瓶药'); assert.deepEqual(s, before); });
test('HOF-U26 death unlock changes real next-run shop prices', () => { const s = death(); walk(s, ['begin-watch', 'cliff', 'rope']); assert.match(view(s).choices.find(x => x.id === 'buy-sabre').label, /5金币/); const old = s.run.gold; walk(s, ['buy-sabre']); assert.equal(old - s.run.gold, 5); });
test('HOF-U27 bread has a real five-food resource effect', () => { const s = shop(), old = s.run.food; walk(s, ['buy-bread']); assert.equal(s.run.food, old + 5); assert.equal(s.run.gold, 13); assert.equal(s.run.bag.includes('bread'), false); });
test('HOF-U28 rescue checks three-food cost and gives nonstacking blessing', () => { const s = walk(shop(), ['leave', 'fight', 'grove']); s.run.food = 2; const before = structuredClone(s); assert.equal(apply(s, 'aid', quiet).kind, 'refused'); assert.deepEqual(s, before); s.run.food = 3; walk(s, ['aid']); assert.equal(s.run.food, 0); assert.equal(s.run.hp, 20); assert.equal(s.run.blessing, true); });
test('HOF-U29 shrine does not sell a duplicate blessing', () => { const s = walk(shop(), ['buy-bread', 'leave', 'fight', 'grove', 'aid']); const before = structuredClone(s); assert.equal(apply(s, 'bless', quiet).reason, '已有灯祝福，不能叠加'); assert.deepEqual(s, before); });
test('HOF-U30 curse money increases next battle counter risk', () => { const s = elite(); assert.equal(s.run.curse, true); assert.equal(s.run.gold, 25); const r = battle(ENEMIES.keeper, 20, 0, 0, false, s.run.curse, quiet); assert.equal(r.chance, 90); });
test('HOF-U31 victory commits reward and first canal unlock together', () => { const s = victory(); assert.equal(s.run.phase, 'victory'); assert.equal(s.profile.wins, 1); assert.deepEqual(s.profile.unlocks, ['canal']); assert.equal(s.run.gold, 20); assert.equal(validate(s), true); });
test('HOF-U32 finished node cannot award victory twice', () => { const s = victory(), before = structuredClone(s); assert.equal(apply(s, 'light', quiet).kind, 'refused'); assert.deepEqual(s, before); });
test('HOF-U33 death loses run resources without victory reward', () => { const s = shop(); walk(s, ['buy-sabre', 'buy-coat', 'buy-tonic', 'leave', 'fight', 'grove', 'forage', 'curse']); const gold = s.run.gold; walk(s, ['fight'], deadly); assert.equal(s.run.phase, 'death'); assert.equal(s.run.gold, Math.floor(gold / 2)); assert.equal(s.run.hp, 0); assert.equal(s.run.food, 0); assert.deepEqual(s.run.bag, []); assert.equal(s.run.weapon, 'none'); assert.equal(s.run.armor, 'none'); assert.equal(s.profile.wins, 0); assert.equal(s.profile.deaths, 1); });
test('HOF-U34 next victory run resets resources but preserves progress', () => { const s = victory(); walk(s, ['begin']); assert.equal(s.profile.wins, 1); assert.equal(s.run.id, 2); assert.equal(s.run.gold, 10); assert.equal(s.run.battles, 0); assert.deepEqual(s.run.visited, []); assert.equal(view(s).choices.find(x => x.id === 'canal').enabled, true); });
test('HOF-U35 natural rule death unlocks equipped watch departure once', () => { const s = death(); assert.deepEqual(s.profile.unlocks, ['watch']); walk(s, ['begin-watch']); assert.equal(s.run.armor, 'coat'); assert.deepEqual(s.run.bag, ['coat']); assert.equal(s.profile.deaths, 1); });
test('HOF-U36 unlocked canal is a working shortcut not text only', () => { const s = victory(); walk(s, ['begin', 'canal']); assert.equal(s.run.node, 'shop'); assert.equal(s.run.food, 7); assert.equal(s.run.hp, 20); assert.deepEqual(s.run.visited, ['fork', 'canal']); });
test('HOF-U37 state rejects unknown fields and impossible health', () => { const s = shop(); s.run.hp = -1; assert.equal(validate(s), false); s.run.hp = 20; s.run.hidden = true; assert.equal(validate(s), false); });
test('HOF-U38 state rejects duplicate or impossible route history', () => { const s = shop(); s.run.visited.push('fork'); assert.equal(validate(s), false); s.run.visited = ['fork', 'elite']; assert.equal(validate(s), false); });
test('HOF-U39 profile unlock claims must agree with outcomes', () => { const s = shop(); s.profile.unlocks.push('canal'); assert.equal(validate(s), false); });
test('HOF-U40 real random snapshot restore resumes identical battle', () => { const a = new Session(game, 42); choose(a, ['begin', 'cliff', 'ore', 'buy-sabre', 'leave']); const saved = a.snapshot(); choose(a, ['fight']); const b = new Session(game, 999); b.restore(saved); choose(b, ['fight']); assert.deepEqual(b.snapshot(), a.snapshot()); });
test('HOF-U41 failure after real battle leaves state RNG log revision atomic', () => { const fragile = { ...game, apply(s, id, random) { const r = apply(s, id, random); if (id === 'fight') throw new Error('after settlement'); return r; } }; const s = new Session(fragile, 42); choose(s, ['begin', 'cliff', 'ore', 'leave']); const before = s.snapshot(), boundary = s.frame().boundary; assert.equal(s.choose('fight').kind, 'failed'); assert.deepEqual(s.snapshot(), before); assert.equal(s.frame().boundary, boundary); });
test('HOF-U42 failed stored JSON or game version load preserves live session', async () => {
  const dir = await fs.mkdtemp(path.join(process.env.HOF_TEST_ROOT, 'store-'));
  try {
    const s = new Session(game, 42); choose(s, ['begin', 'cliff']); const before = s.snapshot(); const store = new Store(dir);
    await fs.writeFile(path.join(dir, 'bad.json'), '{broken'); await assert.rejects(store.load(s, 'bad'), e => e.code === 'SAVE_JSON'); assert.deepEqual(s.snapshot(), before);
    const bad = structuredClone(before); bad.game.version = 2; await fs.writeFile(path.join(dir, 'wrong.json'), JSON.stringify(bad)); await assert.rejects(store.load(s, 'wrong'), e => e.code === 'SAVE_GAME'); assert.deepEqual(s.snapshot(), before);
    await store.save(s, 'good'); choose(s, ['ore']); await store.load(s, 'good'); assert.deepEqual(s.snapshot(), before);
  } finally { await fs.rm(dir, { recursive: true, force: true }); }
});
